export const HANDLE_ROLE_STARTED = "HANDLE_ROLE_STARTED";
export const HANDLE_ROLE_FINISHED = "HANDLE_ROLE_FINISHED";
export const HANDLE_ROLE_ERROR = "HANDLE_ROLE_ERROR";

export const GET_ROLES_FINISHED = "GET_ROLES_FINISHED";
export const GET_ROLE_FINISHED = "GET_ROLE_FINISHED";
export const CREATE_ROLE_FINISHED = "CREATE_ROLE_FINISHED";
export const UPDATE_ROLE_FINISHED = "UPDATE_ROLE_FINISHED";
export const DELETE_ROLE_FINISHED = "DELETE_ROLE_FINISHED";