// handle started
export const HANDLE_USER_STARTED = "HANDLE_USER_STARTED";
export const HANDLE_USER_FINISHED = "HANDLE_USER_FINISHED";
export const HANDLE_USER_ERROR = "HANDLE_USER_ERROR";

export const REGISTER_USER_FINISHED = "REGISTER_USER_FINISHED";
export const LOGIN_USER_FINISHED = "LOGIN_USER_FINISHED";
export const IS_USER_AUTH_FINISHED = "IS_USER_AUTH_FINISHED";
export const ADD_TOKEN = "ADD_TOKEN";
export const GET_PERMISSIONS_FINISHED = "GET_PERMISSIONS_FINISHED";


export const GET_USERS_FINISHED = "GET_USERS_FINISHED";
export const GET_USER_FINSIHED = "GET_USER_FINISHED";
export const UPDATE_USER_FINISHED = "UPDATE_USER_FINISHED";
export const DELETE_USER_FINISHED = "DELETE_USER_FINISHED";

export const LOG_OUT = "LOG_OUT";