// handle started
export const HANDLE_CATEGORY_STARTED = "HANDLE_CATEGORY_STARTED";
export const HANDLE_CATEGORY_FINISHED = "HANDLE_CATEGORY_FINISHED";
export const HANDLE_CATEGORY_ERROR = "HANDLE_CATEGORY_ERROR";


export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORY = "GET_CATEGORY";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
