// handle started
export const HANDLE_EBOOK_STARTED = "HANDLE_EBOOK_STARTED";
export const HANDLE_EBOOK_FINISHED = "HANDLE_EBOOK_FINISHED";
export const HANDLE_EBOOK_ERROR = "HANDLE_EBOOK_ERROR";


export const GET_EBOOKS = "GET_EBOOKS";
export const GET_EBOOK = "GET_EBOOK";
export const ADD_EBOOK = "ADD_EBOOK";
export const EDIT_EBOOK = "EDIT_EBOOK";

export const GET_USER_EBOOKS = "GET_USER_EBOOKS";
export const GET_USER_EBOOK = "GET_USER_EBOOK";
export const ADD_USER_EBOOK = "ADD_USER_EBOOK";
export const EDIT_USER_EBOOK = "EDIT_USER_EBOOK";


export const SELECT_EBOOK = "SELECT_EBOOK";
export const SELECT_USER_EBOOK = "SELECT_USER_EBOOK";